local defaults = {
  terminal = "SUPER + RETURN",
  browser = "SUPER + SHIFT + RETURN",
  file_manager = "SUPER + SHIFT + F",
  file_manager_cwd = "SUPER + ALT + SHIFT + F",
  browser_1 = "SUPER + SHIFT + B",
  browser_private = "SUPER + SHIFT + ALT + B",
  editor = "SUPER + SHIFT + N",
  tmux = "SUPER + ALT + RETURN",
  herdr = "SUPER + CTRL + RETURN",
  music = "SUPER + SHIFT + M",
  music_tui = "SUPER + SHIFT + ALT + M",
  docker = "SUPER + SHIFT + D",
  signal = "SUPER + SHIFT + G",
  obsidian = "SUPER + SHIFT + O",
  omawrite = "SUPER + SHIFT + W",
  passwords = "SUPER + SHIFT + SLASH",
  chatgpt = "SUPER + SHIFT + A",
  grok = "SUPER + SHIFT + ALT + A",
  calendar = "SUPER + SHIFT + C",
  email = "SUPER + SHIFT + E",
  new_email = "SUPER + SHIFT + ALT + E",
  youtube = "SUPER + SHIFT + Y",
  whatsapp = "SUPER + SHIFT + ALT + G",
  google_messages = "SUPER + SHIFT + CTRL + G",
  google_photos = "SUPER + SHIFT + P",
  google_maps = "SUPER + SHIFT + S",
  x = "SUPER + SHIFT + X",
  x_post = "SUPER + SHIFT + ALT + X",
  universal_copy = "SUPER + C",
  universal_paste = "SUPER + V",
  universal_cut = "SUPER + X",
  clipboard_manager = "SUPER + CTRL + V",
  volume_up = "XF86AudioRaiseVolume",
  volume_down = "XF86AudioLowerVolume",
  mute = "XF86AudioMute",
  mute_microphone = "XF86AudioMicMute",
  brightness_up = "XF86MonBrightnessUp",
  brightness_down = "XF86MonBrightnessDown",
  brightness_maximum = "SHIFT + XF86MonBrightnessUp",
  brightness_minimum = "SHIFT + XF86MonBrightnessDown",
  keyboard_brightness_up = "XF86KbdBrightnessUp",
  keyboard_brightness_down = "XF86KbdBrightnessDown",
  keyboard_backlight_cycle = "XF86KbdLightOnOff",
  toggle_touchpad = "XF86TouchpadToggle",
  enable_touchpad = "XF86TouchpadOn",
  disable_touchpad = "XF86TouchpadOff",
  volume_up_precise = "ALT + XF86AudioRaiseVolume",
  volume_down_precise = "ALT + XF86AudioLowerVolume",
  brightness_up_precise = "ALT + XF86MonBrightnessUp",
  brightness_down_precise = "ALT + XF86MonBrightnessDown",
  next_track = "XF86AudioNext",
  next_track_1 = "ALT + XF86AudioPlay",
  pause = "XF86AudioPause",
  play = "XF86AudioPlay",
  previous_track = "XF86AudioPrev",
  previous_track_2 = "ALT + SHIFT + XF86AudioPlay",
  eject_media = "XF86Eject",
  switch_audio_output = "SHIFT + XF86AudioMute",
  switch_media_source = "SHIFT + XF86AudioPause",
  switch_media_source_3 = "SHIFT + XF86AudioPlay",
  close_window = "SUPER + W",
  close_all_windows = "CTRL + ALT + DELETE",
  toggle_window_split = "SUPER + J",
  pseudo_window = "SUPER + P",
  toggle_window_floating_tiling = "SUPER + T",
  full_screen = "SUPER + F",
  tiled_full_screen = "SUPER + CTRL + F",
  full_width = "SUPER + ALT + F",
  pop_window_out_float_pin = "SUPER + O",
  save_window_width = "SUPER + ALT + Home",
  restore_window_width = "SUPER + Home",
  toggle_workspace_layout = "SUPER + L",
  focus_on_left_window = "SUPER + LEFT",
  focus_on_right_window = "SUPER + RIGHT",
  focus_on_above_window = "SUPER + UP",
  focus_on_below_window = "SUPER + DOWN",
  toggle_scratchpad = "SUPER + S",
  move_window_to_scratchpad = "SUPER + ALT + S",
  next_workspace = "SUPER + TAB",
  previous_workspace = "SUPER + SHIFT + TAB",
  former_workspace = "SUPER + CTRL + TAB",
  move_workspace_to_left_monitor = "SUPER + SHIFT + ALT + LEFT",
  move_workspace_to_right_monitor = "SUPER + SHIFT + ALT + RIGHT",
  move_workspace_to_up_monitor = "SUPER + SHIFT + ALT + UP",
  move_workspace_to_down_monitor = "SUPER + SHIFT + ALT + DOWN",
  swap_window_to_the_left = "SUPER + SHIFT + LEFT",
  swap_window_to_the_right = "SUPER + SHIFT + RIGHT",
  swap_window_up = "SUPER + SHIFT + UP",
  swap_window_down = "SUPER + SHIFT + DOWN",
  focus_on_next_window = "ALT + TAB",
  focus_on_previous_window = "ALT + SHIFT + TAB",
  reveal_active_window_on_top = "ALT + TAB",
  reveal_active_window_on_top_1 = "ALT + SHIFT + TAB",
  focus_on_next_monitor = "CTRL + ALT + TAB",
  focus_on_previous_monitor = "CTRL + ALT + SHIFT + TAB",
  expand_window_left = "SUPER + code:20",
  shrink_window_left = "SUPER + code:21",
  shrink_window_up = "SUPER + SHIFT + code:20",
  expand_window_down = "SUPER + SHIFT + code:21",
  expand_window_left_a_little = "SUPER + ALT + code:20",
  shrink_window_left_a_little = "SUPER + ALT + code:21",
  shrink_window_up_a_little = "SUPER + SHIFT + ALT + code:20",
  expand_window_down_a_little = "SUPER + SHIFT + ALT + code:21",
  expand_window_left_a_lot = "SUPER + CTRL + code:20",
  shrink_window_left_a_lot = "SUPER + CTRL + code:21",
  shrink_window_up_a_lot = "SUPER + CTRL + SHIFT + code:20",
  expand_window_down_a_lot = "SUPER + CTRL + SHIFT + code:21",
  scroll_active_workspace_forward = "SUPER + mouse_down",
  scroll_active_workspace_backward = "SUPER + mouse_up",
  move_window = "SUPER + mouse:272",
  resize_window = "SUPER + mouse:273",
  toggle_window_grouping = "SUPER + G",
  move_active_window_out_of_group = "SUPER + ALT + G",
  move_window_to_group_on_left = "SUPER + ALT + LEFT",
  move_window_to_group_on_right = "SUPER + ALT + RIGHT",
  move_window_to_group_on_top = "SUPER + ALT + UP",
  move_window_to_group_on_bottom = "SUPER + ALT + DOWN",
  next_window_in_group = "SUPER + ALT + TAB",
  previous_window_in_group = "SUPER + ALT + SHIFT + TAB",
  move_grouped_window_focus_left = "SUPER + CTRL + LEFT",
  move_grouped_window_focus_right = "SUPER + CTRL + RIGHT",
  next_window_in_group_2 = "SUPER + ALT + mouse_down",
  previous_window_in_group_3 = "SUPER + ALT + mouse_up",
  monitor_scaling_up = "SUPER + SLASH",
  monitor_scaling_down = "SUPER + ALT + SLASH",
  omarchy_menu = "SUPER + SPACE",
  apps_menu = "SUPER + ALT + SPACE",
  emojis = "SUPER + CTRL + E",
  capture_menu = "SUPER + CTRL + C",
  toggle_menu = "SUPER + CTRL + O",
  hardware_menu = "SUPER + CTRL + H",
  omarchy_menu_1 = "SUPER + SHIFT + code:201",
  system_menu = "SUPER + ESCAPE",
  power_menu = "XF86PowerOff",
  keybindings = "SUPER + K",
  tmux_keybindings = "SUPER + ALT + K",
  herdr_keybindings = "SUPER + CTRL + K",
  calculator = "SUPER + CTRL + Q",
  calculator_2 = "XF86Calculator",
  toggle_top_bar = "SUPER + SHIFT + SPACE",
  background_switcher = "SUPER + CTRL + SPACE",
  theme_menu = "SUPER + SHIFT + CTRL + SPACE",
  toggle_window_transparency = "SUPER + BACKSPACE",
  toggle_window_gaps = "SUPER + SHIFT + BACKSPACE",
  toggle_single_window_square_aspect = "SUPER + CTRL + BACKSPACE",
  dismiss_last_notification = "SUPER + comma",
  dismiss_all_notifications = "SUPER + SHIFT + comma",
  toggle_silencing_notifications = "SUPER + CTRL + comma",
  invoke_last_notification = "SUPER + ALT + comma",
  open_notification_history = "SUPER + SHIFT + ALT + comma",
  toggle_locking_on_idle = "SUPER + CTRL + I",
  toggle_nightlight = "SUPER + CTRL + N",
  toggle_laptop_display = "SUPER + CTRL + Delete",
  toggle_laptop_display_mirroring = "SUPER + CTRL + ALT + Delete",
  screenshot = "PRINT",
  screenrecording = "ALT + PRINT",
  make_webcam_overlay_smaller = "SUPER + ALT + code:34",
  make_webcam_overlay_larger = "SUPER + ALT + code:35",
  color_picker = "SUPER + PRINT",
  extract_text_ocr_from_screenshot = "SUPER + CTRL + PRINT",
  share = "SUPER + CTRL + S",
  transcode = "SUPER + CTRL + PERIOD",
  set_reminder = "SUPER + CTRL + R",
  show_reminders = "SUPER + CTRL + ALT + R",
  clear_reminders = "SUPER + SHIFT + CTRL + R",
  show_time = "SUPER + CTRL + ALT + T",
  show_battery_remaining = "SUPER + CTRL + ALT + B",
  toggle_weather = "SUPER + CTRL + ALT + W",
  agent = "SUPER + SHIFT + CTRL + A",
  audio = "SUPER + CTRL + A",
  bluetooth = "SUPER + CTRL + B",
  display = "SUPER + CTRL + D",
  calendar_3 = "SUPER + CTRL + ALT + D",
  network = "SUPER + CTRL + W",
  power = "SUPER + CTRL + P",
  activity = "SUPER + CTRL + T",
  zoom_in = "SUPER + CTRL + Z",
  reset_zoom = "SUPER + CTRL + ALT + Z",
  lock_system = "SUPER + CTRL + L",
  toggle_dictation = "SUPER + CTRL + X",
  start_dictation_push_to_talk = "F9",
  stop_dictation_push_to_talk = "F9",
  lid_switch_on = "switch:on:Lid Switch",
  lid_switch_off = "switch:off:Lid Switch",
}

-- Dynamic loop bindings
for workspace = 1, 10 do
  local key = "code:" .. tostring(workspace + 9)
  defaults["switch_to_workspace_" .. workspace] = "SUPER + " .. key
  defaults["move_window_to_workspace_" .. workspace] = "SUPER + SHIFT + " .. key
  defaults["move_window_silently_to_workspace_" .. workspace] = "SUPER + SHIFT + ALT + " .. key
end

for index = 1, 5 do
  defaults["switch_to_group_window_" .. index] = "SUPER + ALT + code:" .. tostring(index + 9)
end

for panel = 1, 9 do
  defaults["bar_panel_" .. panel] = "SUPER + CTRL + code:" .. tostring(panel + 9)
end

_G.omarchy_bindings = {}

-- Merge defaults
for k, v in pairs(defaults) do
  _G.omarchy_bindings[k] = v
end

-- Merge user provided bindings
if type(_G.omarchy_custom_bindings) == "table" then
  for k, v in pairs(_G.omarchy_custom_bindings) do
    _G.omarchy_bindings[k] = v
  end
end

-- If user wants strict mode, remove bindings not defined by them
if _G.omarchy_bindings_merge == false then
  _G.omarchy_bindings = _G.omarchy_custom_bindings or {}
end
