# Detect T2 MacBook models using PCI IDs
# Vendor: 106b (Apple), Device IDs: 1801 or 1802 (T2 Security Chip)
if lspci -nn | grep -q "106b:180[12]"; then
  echo "Detected MacBook with T2 chip. Installing support items..."

  omarchy-pkg-add \
    linux-t2 \
    linux-t2-headers \
    apple-t2-audio-config \
    apple-bcm-firmware \
    t2fanrd \
    tiny-dfr

  # Add user to video group (required for tiny-dfr to access /dev/dri devices)
  sudo usermod -aG video ${USER}

  # Enable T2 services
  sudo systemctl enable t2fanrd.service
  sudo systemctl enable tiny-dfr.service

  echo "apple-bce" | sudo tee /etc/modules-load.d/t2.conf >/dev/null

  echo "MODULES+=(apple-bce usbhid hid_apple hid_generic xhci_pci xhci_hcd)" | sudo tee /etc/mkinitcpio.conf.d/apple-t2.conf >/dev/null

  cat <<EOF | sudo tee /etc/modprobe.d/brcmfmac.conf >/dev/null
# Fix for T2 MacBook WiFi connectivity issues
options brcmfmac feature_disable=0x82000
EOF

  sudo mkdir -p /etc/limine-entry-tool.d
  cat <<EOF | sudo tee /etc/limine-entry-tool.d/t2-mac.conf >/dev/null
# Generated by Omarchy installer for T2 Mac support
KERNEL_CMDLINE[default]+=" intel_iommu=on iommu=pt pcie_ports=compat mem_sleep_default=s2idle"
EOF

  # T2 Macs cannot use S3 (deep) sleep — force s2idle (freeze) mode
  sudo mkdir -p /etc/systemd/sleep.conf.d
  cat <<EOF | sudo tee /etc/systemd/sleep.conf.d/t2-suspend.conf >/dev/null
[Sleep]
SuspendState=freeze
EOF

  # Manage T2 modules and PCI power states around suspend:
  # - Disable d3cold on Apple NVMe and T2 Bridge to prevent wake failures
  # - Unload brcmfmac (WiFi) to avoid D3 suspend timeout
  # - Unload apple-bce (keyboard/trackpad) to ensure clean resume
  cat <<'EOF' | sudo tee /etc/systemd/system/omarchy-suspend-t2.service >/dev/null
[Unit]
Description=Manage T2 modules around suspend
Before=sleep.target
StopWhenUnneeded=yes

[Service]
User=root
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'for dev in /sys/bus/pci/devices/*/; do vendor=$(cat "$dev/vendor" 2>/dev/null); device=$(cat "$dev/device" 2>/dev/null); if [[ "$vendor" == "0x106b" ]] && [[ "$device" == "0x2005" || "$device" == "0x1801" || "$device" == "0x1802" ]]; then echo 0 > "$dev/d3cold_allowed" 2>/dev/null; fi; done; rmmod brcmfmac_wcc 2>/dev/null; rmmod brcmfmac 2>/dev/null; rmmod -f apple-bce 2>/dev/null'
ExecStop=/bin/bash -c 'modprobe apple-bce; sleep 2; modprobe brcmfmac'

[Install]
WantedBy=sleep.target
EOF

  sudo systemctl enable omarchy-suspend-t2.service
  sudo systemctl daemon-reload
fi
