# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
#
# Use VSCode instead of neovim as your default editor
# export EDITOR="code"
#
# Set a custom prompt with the directory revealed, starship must be turned off
# PS1="\W \[\e]0;\w\a\]$PS1"

# Omarchy ships with a simple starship prompt. Remove the section below
# to turn it off.
if command -v starship &>/dev/null; then
  eval "$(starship init bash)"
fi
