echo "Add tmux theme source-file for themed overrides"

tmux_config="$HOME/.config/tmux/tmux.conf"
source_line='source-file -q ~/.local/state/omarchy/current/theme/tmux-theme.conf'

if [[ -f $tmux_config ]] && ! grep -qF "$source_line" "$tmux_config"; then
  tmp=$(mktemp)

  # Append the source-file line with a blank line and comment before it.
  if awk '
    { print }

    END {
      print ""
      print "# Theme overrides from the active Omarchy theme (generated by"
      print "# omarchy-theme-colors-tmux or the tmux-theme.conf.tpl template)."
      print "'"$source_line"'"
    }
  ' "$tmux_config" >"$tmp"; then
    if ! cmp -s "$tmp" "$tmux_config"; then
      cat "$tmp" >"$tmux_config"
      omarchy-restart-tmux 2>/dev/null || true
    fi
  else
    echo "Could not rewrite $tmux_config; add the tmux theme source-file by hand."
  fi

  rm -f "$tmp"
fi
