# Disable mouse focus (see https://github.com/basecamp/omarchy/pull/5183#issuecomment-4189299971)
windowrule {
    name = jetbrains-focus
    no_follow_mouse = on
    match:class = ^(jetbrains-.*)$
}

# Prevent floating popup windows (tooltips, panel previews) from stealing focus on hover (see https://github.com/basecamp/omarchy/issues/5601)
windowrule {
    name = jetbrains-tooltip
    no_initial_focus = on
    match:class = ^(jetbrains-.*)$
    match:title = ^(win.*)$
    match:float = 1
}