omarchy-refresh-applications
xdg-settings set default-web-browser chromium.desktop
# HEY.desktop is generated by install/packaging/webapps.sh, so the mapping
# can't ship as a static /etc/skel/.config/mimeapps.list entry.
xdg-mime default HEY.desktop x-scheme-handler/mailto
