# Most MIME default mappings now ship as config/mimeapps.list (via /etc/skel
# for new users; existing users keep their own). This script handles the
# runtime side: refresh applications, set Chromium as the system default web
# browser (omarchy-install-browser overrides if the user picks something
# else later), and wire HEY.desktop as the mailto handler — HEY.desktop is
# generated by install/packaging/webapps.sh at install time so it can't
# live in /etc/skel/.config/mimeapps.list.
omarchy-refresh-applications
xdg-settings set default-web-browser chromium.desktop
xdg-mime default HEY.desktop x-scheme-handler/mailto
