[ui.window.box]
width = 664
min_width = 664
max_width = 664
height = 386
min_height = 386
max_height = 386

# List constraints are critical - without these, the window shrinks when empty
[ui.window.box.scroll.list]
height = 300
min_height = 300
max_height = 300

[ui.window.box.scroll.list.item.icon]
pixel_size = 40
