{
  "$schema": "https://raw.githubusercontent.com/earendil-works/pi-mono/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
  "name": "omarchy-system",
  "vars": {
    "bg": "{{ bg }}",
    "fg": "{{ fg }}",
    "accent": "{{ accent }}",
    "selectionBg": "{{ selectionBg }}",
    "selectionFg": "{{ selectionFg }}",
    "black": "{{ black }}",
    "red": "{{ red }}",
    "green": "{{ green }}",
    "yellow": "{{ yellow }}",
    "blue": "{{ blue }}",
    "magenta": "{{ magenta }}",
    "cyan": "{{ cyan }}",
    "white": "{{ white }}",
    "brightBlack": "{{ brightBlack }}",
    "brightRed": "{{ brightRed }}",
    "brightGreen": "{{ brightGreen }}",
    "brightYellow": "{{ brightYellow }}",
    "brightBlue": "{{ brightBlue }}",
    "brightMagenta": "{{ brightMagenta }}",
    "brightCyan": "{{ brightCyan }}",
    "brightWhite": "{{ brightWhite }}",
    "panel": "{{ panel }}",
    "panelAlt": "{{ panelAlt }}",
    "panelPending": "{{ panelPending }}",
    "panelSuccess": "{{ panelSuccess }}",
    "panelError": "{{ panelError }}",
    "border": "{{ border }}",
    "borderMuted": "{{ borderMuted }}",
    "mutedText": "{{ mutedText }}",
    "dimText": "{{ dimText }}"
  },
  "colors": {
    "accent": "accent",
    "border": "border",
    "borderAccent": "accent",
    "borderMuted": "borderMuted",
    "success": "green",
    "error": "red",
    "warning": "yellow",
    "muted": "mutedText",
    "dim": "dimText",
    "text": "fg",
    "thinkingText": "dimText",
    "selectedBg": "selectionBg",
    "userMessageBg": "panel",
    "userMessageText": "fg",
    "customMessageBg": "panel",
    "customMessageText": "fg",
    "customMessageLabel": "accent",
    "toolPendingBg": "panelPending",
    "toolSuccessBg": "panelSuccess",
    "toolErrorBg": "panelError",
    "toolTitle": "accent",
    "toolOutput": "fg",
    "mdHeading": "magenta",
    "mdLink": "accent",
    "mdLinkUrl": "cyan",
    "mdCode": "cyan",
    "mdCodeBlock": "fg",
    "mdCodeBlockBorder": "borderMuted",
    "mdQuote": "mutedText",
    "mdQuoteBorder": "borderMuted",
    "mdHr": "borderMuted",
    "mdListBullet": "magenta",
    "toolDiffAdded": "green",
    "toolDiffRemoved": "red",
    "toolDiffContext": "mutedText",
    "syntaxComment": "dimText",
    "syntaxKeyword": "magenta",
    "syntaxFunction": "blue",
    "syntaxVariable": "accent",
    "syntaxString": "green",
    "syntaxNumber": "yellow",
    "syntaxType": "blue",
    "syntaxOperator": "magenta",
    "syntaxPunctuation": "mutedText",
    "thinkingOff": "borderMuted",
    "thinkingMinimal": "accent",
    "thinkingLow": "blue",
    "thinkingMedium": "magenta",
    "thinkingHigh": "yellow",
    "thinkingXhigh": "red",
    "bashMode": "yellow"
  },
  "export": {
    "pageBg": "{{ bg }}",
    "cardBg": "{{ panel }}",
    "infoBg": "{{ panelAlt }}"
  }
}
