accent = "#f2fcff"
cursor = "#f2fcff"
foreground = "#d6e2ee"
background = "#16242d"
selection_foreground = "#1b2d40"
selection_background = "#4d9ed3"

bg = "#16242d"
lighter_bg = "#1b2d40"
selection = "#243d56"
muted = "#304860"
dark_fg = "#4d86b0"
fg = "#6fa4c9"
light_fg = "#d6e2ee"
bright_fg = "#f2fcff"

red = "#4d86b0"
yellow = "#6fa4c9"
orange = "#8bc9eb"
green = "#5e95bc"
cyan = "#b4e4f6"
blue = "#6fb8e3"
purple = "#8bc9eb"
brown = "#456475"
dark_bg = "#101b21"
darker_bg = "#0b1216"
bright_red = "#73a6cb"
bright_yellow = "#9dcae5"
bright_green = "#86b7d8"
bright_cyan = "#d1eef8"
bright_blue = "#f2fcff"
bright_purple = "#b1d8ee"
