#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

run_node_test <<'JS'
const fs = require('fs')
const manifest = JSON.parse(fs.readFileSync(root + '/shell/plugins/panels/clock/manifest.json', 'utf8'))
const service = fs.readFileSync(root + '/shell/plugins/panels/clock/Service.qml', 'utf8')
const solver = fs.readFileSync(root + '/shell/plugins/panels/clock/PlannerSolver.js', 'utf8')
const dateTimeField = fs.readFileSync(root + '/shell/plugins/panels/clock/PlannerDateTimeField.qml', 'utf8')
const eventEditor = fs.readFileSync(root + '/shell/plugins/panels/clock/EventEditor.qml', 'utf8')
const taskEditor = fs.readFileSync(root + '/shell/plugins/panels/clock/TaskEditor.qml', 'utf8')
const settingsEditor = fs.readFileSync(root + '/shell/plugins/panels/clock/PlannerSettings.qml', 'utf8')
const availabilityEditor = fs.readFileSync(root + '/shell/plugins/panels/clock/AvailabilityEditor.qml', 'utf8')
const proposalReview = fs.readFileSync(root + '/shell/plugins/panels/clock/ProposalReview.qml', 'utf8')
const plannerView = fs.readFileSync(root + '/shell/plugins/panels/clock/PlannerView.qml', 'utf8')
const widget = fs.readFileSync(root + '/shell/plugins/panels/clock/BarWidget.qml', 'utf8')
const panel = fs.readFileSync(root + '/shell/plugins/panels/clock/Panel.qml', 'utf8')

assert(manifest.kinds.includes('service'), 'clock manifest declares a service')
assert(manifest.kinds.includes('bar-widget'), 'clock manifest retains the bar widget')
assertEqual(manifest.entryPoints.service, 'Service.qml', 'clock manifest points at the service')
assertEqual(manifest.entryPoints.barWidget, 'BarWidget.qml', 'clock manifest retains the widget entry point')
assert(service.includes('atomicWrites: true'), 'calendar state uses atomic FileView writes')
assert(service.includes('watchChanges: true'), 'calendar state watches external changes')
assert(service.includes('onFileChanged: reload()'), 'calendar state reloads when another process changes the file')
assert(service.includes('XDG_STATE_HOME'), 'calendar state respects XDG_STATE_HOME')
assert(service.includes('command: ["mkdir", "-p", root.stateHome + "/omarchy"]'), 'calendar service creates its state directory')
assert(service.includes('id: persistTimer'), 'calendar service debounces state writes')
assert(service.includes('import "PlannerSolver.js" as PlannerSolver'), 'service imports the in-tree planner')
assert(service.includes('PlannerSolver.solve(request)'), 'service invokes the in-tree planner')
assert(!service.includes('solverProcess'), 'service does not start an external planner process')
assert(!service.includes('omarchy-calendar-solver'), 'service has no package dependency')
assert(solver.includes('function solve(request)'), 'in-tree planner exposes a pure solve function')
assert(solver.includes('expandBusy'), 'in-tree planner expands recurring busy events')
assert(solver.includes('fitsAvailability'), 'in-tree planner enforces weekly availability')
assert(solver.includes('recoveryPenalty'), 'in-tree planner accounts for cognitive recovery')
assert(dateTimeField.includes('ClockModel.monthGrid'), 'planner date input renders a calendar picker')
assert(dateTimeField.includes('function chooseDay(day)'), 'planner date input accepts a selected calendar day')
assert(dateTimeField.includes('function moveDay(delta)'), 'planner date input supports keyboard date navigation')
assert(dateTimeField.includes('HH:MM'), 'planner date input keeps time entry simple')
assert(eventEditor.includes('PlannerDateTimeField'), 'event editor uses the visual date input')
assert(taskEditor.includes('PlannerDateTimeField'), 'task editor uses the visual date input')
assert(!eventEditor.includes('ISO dates'), 'event editor does not ask users for ISO dates')
assert(!taskEditor.includes('ISO date'), 'task editor does not ask users for ISO dates')
assert(plannerView.includes('"task" in item') && plannerView.includes('"event" in item'), 'editor loader assigns only to matching editor types')
assert(plannerView.includes('? editorLoader.item') && plannerView.includes(': null'), 'editor signals connect only to a loaded editor')
assert(plannerView.includes('ignoreUnknownSignals: true'), 'editor signal connection tolerates proposal-only editors')
assert(plannerView.includes('editorImplicitHeight'), 'planner exposes the active editor height to the popup')
assert(panel.includes('plannerLoader.item.editorImplicitHeight'), 'clock popup sizes itself from the active editor')
assert(eventEditor.includes('implicitHeight: form.implicitHeight'), 'event input modal sizes itself from its form')
assert(taskEditor.includes('implicitHeight: form.implicitHeight'), 'task input modal sizes itself from its form')
assert(settingsEditor.includes('form.implicitHeight'), 'settings input modal sizes itself from its form')
assert(availabilityEditor.includes('form.implicitHeight'), 'availability input modal sizes itself from its form')
assert(proposalReview.includes('signal saved()') && proposalReview.includes('root.saved()'), 'applying a proposal closes the review before another view opens')
assert(!eventEditor.includes('Flickable'), 'event input modal does not scroll')
assert(!taskEditor.includes('Flickable'), 'task input modal does not scroll')
assert(settingsEditor.includes('ScrollView') && settingsEditor.includes('id: bodyScroll') && settingsEditor.includes('ScrollBar.vertical.policy') && settingsEditor.includes('anchors.bottom: footer.top'), 'settings body scrolls while actions stay visible')
assert(availabilityEditor.includes('ScrollView') && availabilityEditor.includes('id: bodyScroll') && availabilityEditor.includes('ScrollBar.vertical.policy') && availabilityEditor.includes('anchors.bottom: footer.top'), 'availability body scrolls while actions stay visible')
assert(plannerView.includes('activeFocus || hot ? Color.foreground : Color.background'), 'primary planner actions stay readable in focus and hover states')
assert(plannerView.includes('ScrollView') && plannerView.includes('ScrollBar.vertical.policy') && plannerView.includes('AgendaView'), 'planner inbox and agenda retain scrolling content')
assert(plannerView.includes('duration.implicitWidth - parent.spacing'), 'planner task rows use their row spacing')
assert(eventEditor.includes('endAtField.forceActiveFocus()'), 'event validation focuses the end date input')
assert(plannerView.includes('Add planning task'), 'plan labels its action as a planning task')
assert(plannerView.includes('Add calendar event'), 'agenda labels its action as a calendar event')
assert(plannerView.includes('Plan tasks'), 'plan exposes an explicit planning action')
assert(plannerView.includes('How planning works'), 'plan explains the review and apply flow')
assert(service.includes('target: "omarchy.calendar"'), 'calendar service exposes the CLI IPC target')
assert(service.includes('function addEvent(inputJson: string)'), 'calendar service exposes event creation over IPC')
assert(service.includes('function addTask(inputJson: string)'), 'calendar service exposes task creation over IPC')
assert(service.includes('function setSettings(patchJson: string)'), 'calendar service exposes settings over IPC')
assert(service.includes('function apply(): string'), 'calendar service exposes explicit Apply over IPC')
assert(service.includes('function plan(): string'), 'calendar service exposes explicit planning over IPC')
assert(service.includes('function returnToInbox(taskId: string)'), 'calendar service exposes Return to inbox over IPC')
assert(service.includes('root.activeRequestId = ""'), 'planner requests are cleared after solving')
assert(service.includes('SystemClock.Minutes'), 'planner watches the system clock for local-midnight refreshes')
assert(widget.includes('serviceFor("omarchy.clock")'), 'bar widget receives the matching service')
assert(widget.includes('function openView(view)'), 'clock widget can open a selected popup view')
assert(widget.includes('function openView(view: string): void'), 'clock widget exposes selected view IPC')
assert(widget.includes('target.service = root.calendarService'), 'bar widget injects service into panel')
assert(panel.includes('property var service: null'), 'panel accepts the injected calendar service')
assert(panel.includes('PlannerView.qml'), 'panel loads the planner view')
assert(fs.existsSync(root + '/shell/plugins/panels/clock/CalendarView.qml'), 'calendar view component exists')
assert(fs.existsSync(root + '/shell/plugins/panels/clock/AgendaView.qml'), 'agenda view component exists')
assert(fs.existsSync(root + '/shell/plugins/panels/clock/ProposalReview.qml'), 'proposal review component exists')
assert(!service.includes('notify-send'), 'planner service does not send raw notifications')
assert(!service.includes('sqlite'), 'planner service does not use SQLite')
assert(!service.includes('curl'), 'planner service does not use a network URL')
assert(!service.includes('systemd'), 'planner service does not add a systemd unit')
JS
