#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

run_node_test <<'JS'
const fs = require('fs')
const manifest = JSON.parse(fs.readFileSync(root + '/shell/plugins/panels/clock/manifest.json', 'utf8'))
const service = fs.readFileSync(root + '/shell/plugins/panels/clock/Service.qml', 'utf8')
const solver = fs.readFileSync(root + '/shell/plugins/panels/clock/PlannerSolver.js', 'utf8')
const widget = fs.readFileSync(root + '/shell/plugins/panels/clock/BarWidget.qml', 'utf8')
const panel = fs.readFileSync(root + '/shell/plugins/panels/clock/Panel.qml', 'utf8')

assert(manifest.kinds.includes('service'), 'clock manifest declares a service')
assert(manifest.kinds.includes('bar-widget'), 'clock manifest retains the bar widget')
assertEqual(manifest.entryPoints.service, 'Service.qml', 'clock manifest points at the service')
assertEqual(manifest.entryPoints.barWidget, 'BarWidget.qml', 'clock manifest retains the widget entry point')
assert(service.includes('atomicWrites: true'), 'calendar state uses atomic FileView writes')
assert(service.includes('watchChanges: true'), 'calendar state watches external changes')
assert(service.includes('onFileChanged: reload()'), 'calendar state reloads when another process changes the file')
assert(service.includes('XDG_STATE_HOME'), 'calendar state respects XDG_STATE_HOME')
assert(service.includes('command: ["mkdir", "-p", root.stateHome + "/omarchy"]'), 'calendar service creates its state directory')
assert(service.includes('id: persistTimer'), 'calendar service debounces state writes')
assert(service.includes('import "PlannerSolver.js" as PlannerSolver'), 'service imports the in-tree planner')
assert(service.includes('PlannerSolver.solve(request)'), 'service invokes the in-tree planner')
assert(!service.includes('solverProcess'), 'service does not start an external planner process')
assert(!service.includes('omarchy-calendar-solver'), 'service has no package dependency')
assert(solver.includes('function solve(request)'), 'in-tree planner exposes a pure solve function')
assert(solver.includes('expandBusy'), 'in-tree planner expands recurring busy events')
assert(solver.includes('fitsAvailability'), 'in-tree planner enforces weekly availability')
assert(solver.includes('recoveryPenalty'), 'in-tree planner accounts for cognitive recovery')
assert(service.includes('target: "omarchy.calendar"'), 'calendar service exposes the CLI IPC target')
assert(service.includes('function addEvent(inputJson: string)'), 'calendar service exposes event creation over IPC')
assert(service.includes('function addTask(inputJson: string)'), 'calendar service exposes task creation over IPC')
assert(service.includes('function setSettings(patchJson: string)'), 'calendar service exposes settings over IPC')
assert(service.includes('function apply(): string'), 'calendar service exposes explicit Apply over IPC')
assert(service.includes('function returnToInbox(taskId: string)'), 'calendar service exposes Return to inbox over IPC')
assert(service.includes('root.activeRequestId = ""'), 'planner requests are cleared after solving')
assert(service.includes('SystemClock.Minutes'), 'planner watches the system clock for local-midnight refreshes')
assert(widget.includes('serviceFor("omarchy.clock")'), 'bar widget receives the matching service')
assert(widget.includes('function openView(view)'), 'clock widget can open a selected popup view')
assert(widget.includes('function openView(view: string): void'), 'clock widget exposes selected view IPC')
assert(widget.includes('target.service = root.calendarService'), 'bar widget injects service into panel')
assert(panel.includes('property var service: null'), 'panel accepts the injected calendar service')
assert(panel.includes('PlannerView.qml'), 'panel loads the planner view')
assert(fs.existsSync(root + '/shell/plugins/panels/clock/CalendarView.qml'), 'calendar view component exists')
assert(fs.existsSync(root + '/shell/plugins/panels/clock/AgendaView.qml'), 'agenda view component exists')
assert(fs.existsSync(root + '/shell/plugins/panels/clock/ProposalReview.qml'), 'proposal review component exists')
assert(!service.includes('notify-send'), 'planner service does not send raw notifications')
assert(!service.includes('sqlite'), 'planner service does not use SQLite')
assert(!service.includes('curl'), 'planner service does not use a network URL')
assert(!service.includes('systemd'), 'planner service does not add a systemd unit')
JS
