#!/bin/bash

set -euo pipefail

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

TEST_HOME=$(mktemp -d)
trap 'rm -rf "$TEST_HOME"' EXIT

FAKE_BIN="$TEST_HOME/bin"
CURRENT_THEME="$TEST_HOME/.local/state/omarchy/current/theme"
mkdir -p "$FAKE_BIN" "$CURRENT_THEME" "$TEST_HOME/.config/gtk-4.0"

cat >"$CURRENT_THEME/gtk.css" <<'EOF'
/* Generated by Omarchy from colors.toml. Overwritten on theme switch. */
@define-color window_bg_color #111c18;
@define-color accent_bg_color #509475;
EOF

cat >"$CURRENT_THEME/colors.toml" <<'EOF'
mode = "dark"
accent = "#509475"
background = "#111c18"
foreground = "#C1C497"
EOF

cat >"$TEST_HOME/.config/gtk-4.0/gtk.css" <<'EOF'
/* leftover user CSS */
@define-color background #000000;
EOF

cat >"$FAKE_BIN/hyprctl" <<'EOF'
#!/bin/bash
if [[ $1 == "clients" ]]; then
  cat "$HYPR_CLIENTS_FILE"
  exit 0
fi
exit 0
EOF

cat >"$FAKE_BIN/pgrep" <<'EOF'
#!/bin/bash
exit 0
EOF

cat >"$FAKE_BIN/pkill" <<'EOF'
#!/bin/bash
exit 0
EOF

cat >"$FAKE_BIN/nautilus" <<'EOF'
#!/bin/bash
printf '%s\n' "$*" >>"$NAUTILUS_LOG"
EOF

cat >"$FAKE_BIN/gsettings" <<'EOF'
#!/bin/bash
printf '%s\n' "$*" >>"$GSETTINGS_LOG"
EOF

cat >"$FAKE_BIN/omarchy-theme-color" <<'EOF'
#!/bin/bash
echo "#509475"
EOF

cat >"$FAKE_BIN/omarchy-launch-nautilus" <<'EOF'
#!/bin/bash
touch "$NAUTILUS_LAUNCHED"
EOF

chmod +x "$FAKE_BIN"/*

printf '[]\n' >"$TEST_HOME/hypr-clients.json"

GSETTINGS_LOG="$TEST_HOME/gsettings.log" \
  NAUTILUS_LAUNCHED="$TEST_HOME/nautilus-launched" \
  NAUTILUS_LOG="$TEST_HOME/nautilus.log" \
  HYPR_CLIENTS_FILE="$TEST_HOME/hypr-clients.json" \
  PATH="$FAKE_BIN:$ROOT/bin:$PATH" \
  HOME="$TEST_HOME" \
  DBUS_SESSION_BUS_ADDRESS="unix:path=/tmp/omarchy-gtk-theme-test" \
  "$ROOT/bin/omarchy-theme-set-gtk"

[[ -f $TEST_HOME/.config/gtk-3.0/gtk.css ]] || fail "GTK 3 css is installed"
[[ -f $TEST_HOME/.config/gtk-4.0/gtk.css ]] || fail "GTK 4 css is installed"
grep -q "window_bg_color #111c18" "$TEST_HOME/.config/gtk-4.0/gtk.css" || fail "GTK 4 css uses the current theme palette"
[[ -f $TEST_HOME/.config/gtk-4.0/gtk.css.pre-omarchy ]] || fail "unmanaged GTK css is backed up before overwrite"
grep -q "leftover user CSS" "$TEST_HOME/.config/gtk-4.0/gtk.css.pre-omarchy" || fail "GTK css backup keeps the previous file"
grep -q "accent-color green" "$TEST_HOME/gsettings.log" || fail "GNOME accent-color follows the theme accent hue"
[[ ! -e $TEST_HOME/nautilus-launched ]] || fail "Files is not opened when no Files window is mapped"
[[ ! -e $TEST_HOME/nautilus.log ]] || fail "Files daemon is left alone when no window is mapped"

cat >"$TEST_HOME/hypr-clients.json" <<'EOF'
[{"class":"org.gnome.Nautilus","mapped":true}]
EOF
rm -f "$TEST_HOME/nautilus-launched" "$TEST_HOME/nautilus.log"

GSETTINGS_LOG="$TEST_HOME/gsettings.log" \
  NAUTILUS_LAUNCHED="$TEST_HOME/nautilus-launched" \
  NAUTILUS_LOG="$TEST_HOME/nautilus.log" \
  HYPR_CLIENTS_FILE="$TEST_HOME/hypr-clients.json" \
  PATH="$FAKE_BIN:$ROOT/bin:$PATH" \
  HOME="$TEST_HOME" \
  DBUS_SESSION_BUS_ADDRESS="unix:path=/tmp/omarchy-gtk-theme-test" \
  "$ROOT/bin/omarchy-theme-set-gtk"

for _ in $(seq 1 20); do
  [[ -e $TEST_HOME/nautilus-launched ]] && break
  sleep 0.05
done

[[ -e $TEST_HOME/nautilus-launched ]] || fail "Files is relaunched when a Files window is mapped"

pass "GTK theme sync installs css and maps accent color"
