#!/bin/bash

set -euo pipefail

# colors-tmux.toml lets an installed theme carry its tmux integration back:
# pure TOML data that omarchy serializes into tmux-theme.conf, so nothing that
# runs code is shipped or executed. This suite locks the schema, the
# serialization, the escape hatch back to the generated template, and the fact
# that hostile strings stay strings.

source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/base-test.sh"

test_tmp=$(mktemp -d)
trap 'rm -rf "$test_tmp"' EXIT

home="$test_tmp/home"
state="$home/.local/state/omarchy/current"
themes="$home/.config/omarchy/themes"
mkdir -p "$state" "$themes"

marker="omarchy-colors-tmux-marker"

set_theme() {
  HOME="$home" OMARCHY_PATH="$ROOT" PATH="$ROOT/bin:$PATH" \
    OMARCHY_THEME_HEADLESS=1 OMARCHY_THEME_SKIP_BACKGROUND=1 \
    XDG_RUNTIME_DIR="$test_tmp" \
    bash "$ROOT/bin/omarchy-theme-set" "$1" 2>"$test_tmp/stderr" || return $?
}

staged() {
  printf '%s' "$state/theme/$1"
}

assert_staged() {
  [[ -f $(staged "$1") ]] || fail "$2"
}

render() {
  HOME="$home" OMARCHY_PATH="$ROOT" PATH="$ROOT/bin:$PATH" \
    bash "$ROOT/bin/omarchy-theme-colors-tmux" "$@"
}

write_noir_config() {
  cat >"$1" <<TOML
schema = 1

[theme]
status_bg = "#1c1c1c"
status_fg = "#c1c1c1"
session_bg = "#8a9a7b"
session_fg = "#0c0b0c"
window_active_fg = "#8a9a7b"
window_inactive_fg = "#666666"
pane_border = "#666666"
pane_active_border = "#8a9a7b"
message_fg = "#8a9a7b"
mode_fg = "#0c0b0c"
mode_bg = "#8a9a7b"
clock_color = "#8a9a7b"
TOML
}

# An installed theme may not ship tmux-theme.conf, but its declarative
# integration replaces the generated one.
noir="$themes/noir-dawn"
mkdir -p "$noir/.git"
cat >"$noir/colors.toml" <<TOML
mode = "dark"
background = "#1c1c1c"
foreground = "#c1c1c1"
accent = "#8a9a7b"
red = "#8a9a7b"
green = "#c1c1c1"
yellow = "#888888"
blue = "#aaaaaa"
magenta = "#999999"
cyan = "#aa9988"
muted = "#666666"
TOML
write_noir_config "$noir/colors-tmux.toml"
printf '# %s\n' "$marker" >"$noir/tmux-theme.conf"

set_theme noir-dawn || fail "omarchy-theme-set applies a theme carrying colors-tmux.toml"

assert_staged colors-tmux.toml "colors-tmux.toml is colour data and is staged"
! grep -q "$marker" "$(staged tmux-theme.conf)" || fail "an installed theme cannot ship tmux-theme.conf itself"
grep -q "#8a9a7b" "$(staged tmux-theme.conf)" || fail "the theme's accent color is serialized"
grep -q "status-style" "$(staged tmux-theme.conf)" || fail "the theme section is serialized"

pass "an installed theme's colors-tmux.toml replaces the generated tmux-theme.conf"

golden="$test_tmp/golden.conf"
cat >"$golden" <<'CONF'
# Tmux theme generated by Omarchy from this theme's colors-tmux.toml.
# Everything below is data serialized from that TOML; edit the theme's TOML,
# not this file.

set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=#1c1c1c,bg=#8a9a7b,bold] #S #[bg=default] "
set -g status-right "#[fg=#8a9a7b]#{?pane_in_mode,COPY ,}#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=#666666]#h "
set -g window-status-format "#[fg=#666666] #I:#W "
set -g window-status-current-format "#[fg=#8a9a7b,bold] #I:#W "
set -g pane-border-style "fg=#666666"
set -g pane-active-border-style "fg=#8a9a7b"
set -g message-style "bg=default,fg=#8a9a7b"
set -g message-command-style "bg=default,fg=#8a9a7b"
set -g mode-style "bg=#8a9a7b,fg=#0c0b0c"
setw -g clock-mode-colour "#8a9a7b"
CONF

diff -u "$golden" "$(staged tmux-theme.conf)" || fail "serialization is deterministic and matches the documented shape"

pass "the serialized tmux-theme.conf matches the documented shape exactly"

# A string value that tries to break out of its quotes is rejected by the hex
# color validation, so the generated template stays in place.
hostile="$themes/hostile"
mkdir -p "$hostile/.git"
cp "$noir/colors.toml" "$hostile/colors.toml"
cat >"$hostile/colors-tmux.toml" <<TOML
schema = 1

[theme]
status_bg = "#1c1c1c"
status_fg = "#c1c1c1"
session_bg = "#8a9a7b"
session_fg = "#0c0b0c"
window_active_fg = "#8a9a7b"
window_inactive_fg = "#666666"
pane_border = "#666666"
pane_active_border = "#8a9a7b"
message_fg = "\"]; run-shell $marker"
mode_fg = "#0c0b0c"
mode_bg = "#8a9a7b"
clock_color = "#8a9a7b"
TOML

set_theme hostile || fail "omarchy-theme-set applies a theme whose strings try to escape"
grep -q "not a valid hex color" "$test_tmp/stderr" || fail "a hostile value is rejected by hex validation"
grep -q "status-style" "$(staged tmux-theme.conf)" || fail "a hostile value keeps the generated default"
! grep -q "$marker" "$(staged tmux-theme.conf)" || fail "a hostile value never becomes a tmux command"

pass "a string that tries to break out of its quotes is rejected by hex validation"

# Anything the schema does not understand keeps the generated default and says
# so, instead of half-applying a theme's tmux config.
invalid_toml="$themes/invalid-toml"
mkdir -p "$invalid_toml/.git"
cp "$noir/colors.toml" "$invalid_toml/colors.toml"
printf '[theme]\nstatus_bg = "#1c1c1c"\n\n[theme.status]\nfoo = "bar\n' >"$invalid_toml/colors-tmux.toml"

set_theme invalid-toml || fail "an unparsable colors-tmux.toml does not break theme-set"
grep -q "status-style" "$(staged tmux-theme.conf)" || fail "an unparsable colors-tmux.toml keeps the generated default"
grep -q "colors-tmux" "$test_tmp/stderr" || fail "an unparsable colors-tmux.toml is named on stderr"

pass "an unparsable colors-tmux.toml falls back to the generated template loudly"

unknown_key="$themes/unknown-key"
mkdir -p "$unknown_key/.git"
cp "$noir/colors.toml" "$unknown_key/colors.toml"
printf 'loadstring = "evil"\n[theme]\nstatus_bg = "#1c1c1c"\n' >"$unknown_key/colors-tmux.toml"

set_theme unknown-key || fail "an unknown top-level key does not break theme-set"
grep -q "does not support the top-level key" "$test_tmp/stderr" || fail "an unknown top-level key is named on stderr"
grep -q "status-style" "$(staged tmux-theme.conf)" || fail "an unknown top-level key keeps the generated default"

pass "keys outside the schema are refused rather than ignored"

bad_schema="$themes/bad-schema"
mkdir -p "$bad_schema/.git"
cp "$noir/colors.toml" "$bad_schema/colors.toml"
printf 'schema = true\n[theme]\nstatus_bg = "#1c1c1c"\n' >"$bad_schema/colors-tmux.toml"

set_theme bad-schema || fail "a boolean schema value does not break theme-set"
grep -q "unsupported schema version" "$test_tmp/stderr" || fail "a boolean schema value is named on stderr"
grep -q "status-style" "$(staged tmux-theme.conf)" || fail "a boolean schema value keeps the generated default"

pass "the schema gate rejects non-integer versions like true"

no_theme="$themes/no-theme"
mkdir -p "$no_theme/.git"
cp "$noir/colors.toml" "$no_theme/colors.toml"
printf 'schema = 1\n' >"$no_theme/colors-tmux.toml"

set_theme no-theme || fail "a missing [theme] section does not break theme-set"
grep -q "defines no" "$test_tmp/stderr" || fail "a missing [theme] is named on stderr"

pass "a missing [theme] section is refused"

# A theme the user wrote gets the same treatment through the same door.
mine="$themes/mine"
mkdir -p "$mine"
cp "$noir/colors.toml" "$mine/colors.toml"
write_noir_config "$mine/colors-tmux.toml"

set_theme mine || fail "omarchy-theme-set applies a user-written theme with colors-tmux.toml"
grep -q "#8a9a7b" "$(staged tmux-theme.conf)" || fail "a user-written theme's colors-tmux.toml is honored"

pass "a user-written theme's colors-tmux.toml is honored too"

# Direct renderer behaviour: losing python3 degrades to a refusal instead of a
# broken file.
values_toml="$test_tmp/values.toml"
cat >"$values_toml" <<TOML
schema = 1

[theme]
status_bg = "#1c1c1c"
status_fg = "#c1c1c1"
session_bg = "#8a9a7b"
session_fg = "#0c0b0c"
window_active_fg = "#8a9a7b"
window_inactive_fg = "#666666"
pane_border = "#666666"
pane_active_border = "#8a9a7b"
message_fg = "#8a9a7b"
mode_fg = "#0c0b0c"
mode_bg = "#8a9a7b"
clock_color = "#8a9a7b"
TOML
values_out="$test_tmp/values-out.conf"
render --file "$values_toml" --out "$values_out" || fail "the renderer reads the documented value zoo"
grep -q "#8a9a7b" "$values_out" || fail "hex colors are serialized as-is in tmux config"

pass "hex colors serialize as-is in tmux config"

out_without_python="$test_tmp/no-python.conf"
if PATH= "$ROOT/bin/omarchy-theme-colors-tmux" --file "$values_toml" --out "$out_without_python" 2>"$test_tmp/stderr"; then
  fail "the renderer refuses to run without python3"
fi
grep -q "python3" "$test_tmp/stderr" || fail "losing python3 is explained on stderr"
[[ ! -e $out_without_python ]] || fail "nothing is written when the renderer refuses"

pass "without python3 the renderer refuses and writes nothing"

bad_args=0
render --file "$values_toml" 2>/dev/null || bad_args=1
(( bad_args == 1 )) || fail "the renderer requires both --file and --out"

pass "the renderer requires both --file and --out"
