$screensaver_timeout = 150          # 2.5min
$lock_timeout = 151                 # 5min
$keyboard_backlight_timeout = 330   # 5.5min
$display_off_timeout = 330          # 5.5min

source = ~/.local/share/omarchy/default/hypr/hypridle.conf
