"$schema" = 'https://starship.rs/config-schema.json'
command_timeout = 750
format = """
[](color_orange)\
$os\
$username\
[](bg:color_green fg:color_orange)\
$hostname\
[](bg:color_yellow fg:color_green)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

palette = 'monokai_pro_ristretto_contrast'

[palettes.monokai_pro_ristretto_contrast]
# Background colors - brightened for better contrast against #2c2525 terminal background
color_bg1 = '#45424a'      # Lighter dark background (was #221f22)
color_bg3 = '#5a575c'      # Brighter dimmed background (was #403e41)

# Foreground
color_fg0 = '#e6d9db'      # Main text color (white)

# Accent colors from Monokai Pro Ristretto (unchanged for vibrancy)
color_red = '#ff6188'      # accent1
color_green = '#a9dc76'    # accent4
color_yellow = '#ffd866'   # accent3
color_orange = '#fc9867'   # accent2
color_blue = '#78dce8'     # Changed to cyan for better contrast with programming languages
color_purple = '#ab9df2'   # accent6 (magenta)
color_aqua = '#ab9df2'     # accent5 (cyan)
color_brown = '#2c2525'
# Additional colors for variety
color_dimmed1 = '#c1c0c0'  # dimmed1
color_dimmed2 = '#939293'  # dimmed2
color_dimmed3 = '#727072'  # dimmed3

[os]
disabled = false
style = "bg:color_orange fg:color_brown"

[os.symbols]
Arch = "󰣇"

[username]
show_always = true
style_user = "bg:color_orange fg:color_fg0"
style_root = "bg:color_orange fg:color_fg0"
format = '[ $user ]($style)'

[hostname]
ssh_only = false
format = '[@$hostname]($style)[$ssh_symbol]($style)'
style = "bg:color_green fg:color_red"
ssh_symbol = " 󰘂  "

[directory]
style = "fg:color_brown bg:color_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = ""

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"code" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_brown bg:color_aqua)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_brown bg:color_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:color_aqua bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:color_aqua bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'

