general {
    col.active_border = rgba(8a8588ee) rgba(e2dddcee)
}

decoration {
    rounding = 3
    rounding_power = 3

    shadow {
      enabled = yes
      render_power = 3
      range = 16
      color = rgba(00000052)
    }
}
