# Detect T2 MacBook models using PCI IDs
# Vendor: 106b (Apple), Device IDs: 1801 or 1802 (T2 Security Chip)
if lspci -nn | grep -q "106b:180[12]"; then
  echo "Detected MacBook with T2 chip. Installing support items..."

  omarchy-pkg-add \
    linux-t2 \
    linux-t2-headers \
    apple-t2-audio-config \
    apple-bcm-firmware \
    t2fanrd \
    tiny-dfr

  # Add user to video group (required for tiny-dfr to access /dev/dri devices)
  sudo usermod -aG video ${USER}

  # Enable T2 services
  sudo systemctl enable t2fanrd.service
  sudo systemctl enable tiny-dfr.service

  echo "apple-bce" | sudo tee /etc/modules-load.d/t2.conf >/dev/null

  echo "MODULES+=(apple-bce usbhid hid_apple hid_generic xhci_pci xhci_hcd)" | sudo tee /etc/mkinitcpio.conf.d/apple-t2.conf >/dev/null

  cat <<EOF | sudo tee /etc/modprobe.d/brcmfmac.conf >/dev/null
# Fix for T2 MacBook WiFi connectivity issues
options brcmfmac feature_disable=0x82000
EOF

  sudo mkdir -p /etc/limine-entry-tool.d
  cat <<EOF | sudo tee /etc/limine-entry-tool.d/t2-mac.conf >/dev/null
# Generated by Omarchy installer for T2 Mac support
KERNEL_CMDLINE[default]+=" intel_iommu=on iommu=pt pcie_ports=compat"
EOF

  omarchy-pkg-add power-profiles-daemon
  sudo systemctl enable power-profiles-daemon.service

  # Auto-switch power profile on AC plug/unplug (overrides generic 99-power-profile.rules for T2)
  cat <<EOF | sudo tee /etc/udev/rules.d/99-power-profile.rules >/dev/null
SUBSYSTEM=="power_supply", ATTR{type}=="Mains", RUN+="$OMARCHY_PATH/bin/omarchy-power-profile"
EOF

  # Set correct power profile at boot
  cat <<EOF | sudo tee /etc/systemd/system/power-profile-boot.service >/dev/null
[Unit]
Description=Set power profile based on AC status at boot
After=power-profiles-daemon.service
Requires=power-profiles-daemon.service

[Service]
Type=oneshot
ExecStart=$OMARCHY_PATH/bin/omarchy-power-profile

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable power-profile-boot.service

  # Toggle WiFi power save based on AC status
  cat <<EOF | sudo tee /etc/udev/rules.d/99-wifi-powersave.rules >/dev/null
SUBSYSTEM=="power_supply", ATTR{type}=="Mains", ATTR{online}=="1", RUN+="$OMARCHY_PATH/bin/omarchy-wifi-powersave off"
SUBSYSTEM=="power_supply", ATTR{type}=="Mains", ATTR{online}=="0", RUN+="$OMARCHY_PATH/bin/omarchy-wifi-powersave on"
EOF

  sudo udevadm control --reload
  sudo udevadm trigger --subsystem-match=power_supply
fi
