accent = "#faa968"
cursor = "#f6dcac"
foreground = "#f6dcac"
background = "#05182e"
selection_foreground = "#00172e"
selection_background = "#faa968"

bg = "#05182e"
lighter_bg = "#0a2540"
selection = "#134e5a"
muted = "#2a6b78"
dark_fg = "#3f8f8a"
fg = "#8cbfb8"
light_fg = "#a7c9c6"
bright_fg = "#f6dcac"

red = "#f85525"
yellow = "#e97b3c"
orange = "#faa968"
green = "#028391"
cyan = "#8cbfb8"
blue = "#3f8f8a"
purple = "#3f8f8a"
brown = "#743d1e"
dark_bg = "#031222"
darker_bg = "#020c17"
bright_red = "#f85525"
bright_yellow = "#e97b3c"
bright_green = "#028391"
bright_cyan = "#8cbfb8"
bright_blue = "#faa968"
bright_purple = "#3f8f8a"
