#!/bin/bash

sudo pacman -S --noconfirm --needed \
  alacritty \
  ansible \
  avahi \
  bash-completion \
  bat \
  blueberry \
  bluetui \
  brightnessctl \
  btop \
  cargo \
  clang \
  cups \
  cups-browsed \
  cups-filters \
  cups-pdf \
  dmidecode \
  dnsmasq \
  docker \
  docker-buildx \
  docker-compose \
  dust \
  evince \
  eza \
  fastfetch \
  fd \
  ffmpegthumbnailer \
  flameshot \
  freerdp \
  fwupd \
  fontconfig \
  fzf \
  gcc14 \
  gnome-calculator \
  gnome-keyring \
  gnome-themes-extra \
  gocryptfs \
  gum \
  gvfs-mtp \
  gvfs-nfs \
  gvfs-smb \
  hypridle \
  hyprland \
  hyprland-qtutils \
  hyprlock \
  hyprpicker \
  hyprshot \
  hyprsunset \
  imagemagick \
  impala \
  imv \
  inetutils \
  iwd \
  jq \
  kvantum-qt5 \
  lazydocker \
  lazygit \
  less \
  libqalculate \
  libreoffice \
  llvm \
  localsend \
  lshw \
  lsof \
  luarocks \
  mako \
  man \
  mariadb-libs \
  micro \
  minicom \
  mise \
  mtr \
  nano \
  nautilus \
  nautilus-python \
  nautilus-share \
  ncdu \
  nfs-utils \
  nftables \
  noto-fonts \
  noto-fonts-cjk \
  noto-fonts-emoji \
  noto-fonts-extra \
  nss-mdns \
  nvim \
  obsidian \
  opentofu \
  pamixer \
  pinta \
  playerctl \
  plocate \
  plymouth \
  polkit-gnome \
  postgresql-libs \
  power-profiles-daemon \
  powertop \
  python-dbus \
  python-gobject \
  python-poetry-core \
  python-terminaltexteffects \
  qemu-desktop \
  rclone \
  remmina \
  resources \
  ristretto \
  rsync \
  qt5-wayland \
  ripgrep \
  satty \
  slurp \
  smbclient \
  starship \
  sushi \
  swaybg \
  swayosd \
  system-config-printer \
  thefuck \
  tldr \
  tree-sitter-cli \
  ttf-cascadia-mono-nerd \
  ttf-jetbrains-mono \
  ttf-ia-writer \
  ttf-jetbrains-mono-nerd \
  tzupdate \
  ufw \
  ufw-docker \
  unzip \
  uwsm \
  virt-manager \
  vivaldi \
  vlc \
  walker-bin \
  waybar \
  wf-recorder \
  wget \
  whois \
  wiremix \
  wireplumber \
  wl-clip-persist \
  wl-clipboard \
  wl-screenrec \
  woff2-font-awesome \
  xdg-desktop-portal-gtk \
  xdg-desktop-portal-hyprland \
  xmlstarlet \
  xorg-xauth \
  xournalpp \
  yaru-icon-theme \
  yay \
  zoxide \
  zsh


yay -S --noconfirm --needed \
  backrest \
  feishin-bin \
  mailspring-bin \
  nomachine \
  packet \
  remote-desktop-manager \
  sirikali-bin \
  tilix \
  visual-studio-code-bin \
  waybar-mpris-git \
  wttrbar
  
systemctl enable backrest@$USER.service
