# General theme information
[theme]
name = "Everforest"
variant = "dark"

# GTK settings
[gtk]
theme = "Adwaita-dark"
color_scheme = "prefer-dark"

# Icon and Cursor settings
[icons]
theme = "Adwaita" 
cursor_theme = "Adwaita" 

# Optional: Font settings
[fonts]
monospace = "JetBrains Mono Nerd Font 10"
sans_serif = "Inter 10"

# Optional: Backgrounds
[[background]]
url = "https://images.unsplash.com/photo-1511884642898-4c92249e20b6?w=1920"

[[background]]
url = "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=1920"

[[background]]
url = "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920"

# Optional: Environment variables specific to this theme
[env]
GTK_THEME_VARIANT = "dark"