### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
#timeout: 3
default_entry: 2
interface_branding: DedSec Bootloader
interface_branding_color: 2
hash_mismatch_panic: no

term_background: 050A0E
backdrop: 050A0E

# Terminal colors (DedSec palette)
term_palette: 050A0E;FF2D6F;00FF41;BFFF00;00E5FF;A77BCA;B0F4E6;B0F4E6
term_palette_bright: 1E3044;FF2D6F;00FF41;BFFF00;00E5FF;A77BCA;B0F4E6;FFFFFF

# Text colors
term_foreground: 00FF41
term_foreground_bright: B0F4E6
term_background_bright: 0A1018
