accent = "#8d8d8d"
cursor = "#ffffff"
foreground = "#ffffff"
background = "#000000"

# Selection colors
selection_foreground = "#000000"
selection_background = "#ffffff"

# Normal colors (ANSI 0-7)
color0 = "#000000"
color1 = "#a4a4a4"
color2 = "#b6b6b6"
color3 = "#cecece"
color4 = "#8d8d8d"
color5 = "#9b9b9b"
color6 = "#b0b0b0"
color7 = "#ececec"

red = "#a4a4a4"
yellow = "#cecece"
orange = "#b9b9b9"
green = "#b6b6b6"
cyan = "#b0b0b0"
blue = "#8d8d8d"
purple = "#9b9b9b"
brown = "#5c5c5c"
dark_bg = "#090909"
darker_bg = "#070707"
bright_red = "#a4a4a4"
bright_yellow = "#cecece"
bright_green = "#b6b6b6"
bright_cyan = "#b0b0b0"
bright_blue = "#8d8d8d"
bright_purple = "#9b9b9b"
