background = {{ background }}
foreground = {{ foreground }}
cursor-color = {{ cursor }}
selection-background = {{ selection_background }}
selection-foreground = {{ selection_foreground }}

palette = 0={{ base08 }}
palette = 1={{ base09 }}
palette = 2={{ base0A }}
palette = 3={{ base0B }}
palette = 4={{ base0C }}
palette = 5={{ base0D }}
palette = 6={{ base0E }}
palette = 7={{ base0F }}
palette = 8={{ base10 }}
palette = 9={{ base11 }}
palette = 10={{ base12 }}
palette = 11={{ base13 }}
palette = 12={{ base14 }}
palette = 13={{ base15 }}
palette = 14={{ base16 }}
palette = 15={{ base17 }}
