background = {{ background }}
foreground = {{ foreground }}
cursor-color = {{ cursor }}
selection-background = {{ selection_background }}
selection-foreground = {{ selection_foreground }}

palette = 0={{ base00 }}
palette = 1={{ base08 }}
palette = 2={{ base0B }}
palette = 3={{ base0A }}
palette = 4={{ base0D }}
palette = 5={{ base0E }}
palette = 6={{ base0C }}
palette = 7={{ base05 }}
palette = 8={{ base03 }}
palette = 9={{ base12 }}
palette = 10={{ base14 }}
palette = 11={{ base13 }}
palette = 12={{ base16 }}
palette = 13={{ base17 }}
palette = 14={{ base15 }}
palette = 15={{ base07 }}
