/* Generated by Omarchy from the active theme. */

:root {
  /* Libadwaita derives the standalone *-color values from these backgrounds. */
  --accent-bg-color: {{ accent }};
  --accent-fg-color: {{ accent_foreground }};

  --destructive-bg-color: {{ red }};
  --destructive-fg-color: {{ red_foreground }};
  --success-bg-color: {{ green }};
  --success-fg-color: {{ green_foreground }};
  --warning-bg-color: {{ yellow }};
  --warning-fg-color: {{ yellow_foreground }};
  --error-bg-color: {{ red }};
  --error-fg-color: {{ red_foreground }};

  --window-bg-color: {{ background }};
  --window-fg-color: {{ foreground }};
  --view-bg-color: {{ background }};
  --view-fg-color: {{ foreground }};

  --headerbar-bg-color: {{ dark_background }};
  --headerbar-fg-color: {{ foreground }};
  --headerbar-border-color: {{ foreground }};
  --headerbar-backdrop-color: {{ darker_background }};
  --headerbar-shade-color: rgb(0 0 0 / 12%);
  --headerbar-darker-shade-color: rgb(0 0 0 / 12%);

  --sidebar-bg-color: {{ dark_background }};
  --sidebar-fg-color: {{ foreground }};
  --sidebar-backdrop-color: {{ darker_background }};
  --sidebar-border-color: rgb(0 0 0 / 7%);
  --sidebar-shade-color: rgb(0 0 0 / 7%);

  --secondary-sidebar-bg-color: {{ darker_background }};
  --secondary-sidebar-fg-color: {{ foreground }};
  --secondary-sidebar-backdrop-color: {{ darker_background }};
  --secondary-sidebar-border-color: rgb(0 0 0 / 7%);
  --secondary-sidebar-shade-color: rgb(0 0 0 / 7%);

  --card-bg-color: {{ lighter_background }};
  --card-fg-color: {{ foreground }};
  --card-shade-color: rgb(0 0 0 / 7%);
  --dialog-bg-color: {{ lighter_background }};
  --dialog-fg-color: {{ foreground }};
  --popover-bg-color: {{ lighter_background }};
  --popover-fg-color: {{ foreground }};
  --popover-shade-color: rgb(0 0 0 / 7%);

  --overview-bg-color: {{ dark_background }};
  --overview-fg-color: {{ foreground }};
  --thumbnail-bg-color: {{ lighter_background }};
  --thumbnail-fg-color: {{ foreground }};
  --active-toggle-bg-color: {{ accent }};
  --active-toggle-fg-color: {{ accent_foreground }};

  --shade-color: rgb(0 0 0 / 7%);
  --scrollbar-outline-color: {{ background }};
}

@media (prefers-color-scheme: dark) {
  :root {
    --headerbar-shade-color: rgb(0 0 0 / 36%);
    --headerbar-darker-shade-color: rgb(0 0 0 / 90%);
    --sidebar-border-color: rgb(0 0 0 / 36%);
    --sidebar-shade-color: rgb(0 0 0 / 25%);
    --secondary-sidebar-border-color: rgb(0 0 0 / 36%);
    --secondary-sidebar-shade-color: rgb(0 0 0 / 25%);
    --card-shade-color: rgb(0 0 0 / 36%);
    --popover-shade-color: rgb(0 0 0 / 25%);
    --shade-color: rgb(0 0 0 / 25%);
  }
}
