/* Generated by Omarchy from colors.toml. Overwritten on theme switch. */

@define-color background {{ background }};
@define-color foreground {{ foreground }};
@define-color black {{ darker_background }};
@define-color red {{ red }};
@define-color green {{ green }};
@define-color yellow {{ yellow }};
@define-color blue {{ blue }};
@define-color magenta {{ magenta }};
@define-color cyan {{ cyan }};
@define-color white {{ foreground }};
@define-color bright_black {{ muted }};
@define-color bright_red {{ bright_red }};
@define-color bright_green {{ bright_green }};
@define-color bright_yellow {{ bright_yellow }};
@define-color bright_blue {{ bright_blue }};
@define-color bright_magenta {{ bright_magenta }};
@define-color bright_cyan {{ bright_cyan }};
@define-color bright_white {{ bright_foreground }};

@define-color accent_bg_color {{ accent }};
@define-color accent_fg_color {{ background }};
@define-color accent_color {{ accent }};

@define-color window_bg_color {{ background }};
@define-color window_fg_color {{ foreground }};

@define-color view_bg_color {{ darker_background }};
@define-color view_fg_color {{ foreground }};
@define-color sidebar_bg_color {{ darker_background }};
@define-color sidebar_fg_color {{ foreground }};
@define-color sidebar_backdrop_color {{ darker_background }};
@define-color sidebar_shade_color {{ darker_background }};

@define-color headerbar_bg_color {{ background }};
@define-color headerbar_fg_color {{ foreground }};
@define-color headerbar_backdrop_color {{ background }};
@define-color headerbar_shade_color {{ darker_background }};
@define-color card_bg_color {{ lighter_background }};
@define-color card_fg_color {{ foreground }};

@define-color popover_bg_color {{ darker_background }};
@define-color popover_fg_color {{ foreground }};

@define-color destructive_bg_color {{ red }};
@define-color destructive_fg_color {{ background }};

@define-color success_bg_color {{ green }};
@define-color success_fg_color {{ background }};

@define-color warning_bg_color {{ yellow }};
@define-color warning_fg_color {{ background }};

@define-color error_bg_color {{ red }};
@define-color error_fg_color {{ background }};

@define-color dialog_bg_color {{ background }};
@define-color dialog_fg_color {{ foreground }};

@define-color borders alpha({{ foreground }}, 0.12);

@define-color theme_fg_color {{ foreground }};
@define-color theme_text_color {{ foreground }};
@define-color theme_bg_color {{ background }};
@define-color theme_base_color {{ darker_background }};
@define-color theme_selected_bg_color {{ selection }};
@define-color theme_selected_fg_color {{ selection_foreground }};
@define-color insensitive_bg_color {{ background }};
@define-color insensitive_fg_color {{ muted }};
@define-color insensitive_base_color {{ darker_background }};
@define-color theme_unfocused_fg_color {{ foreground }};
@define-color theme_unfocused_text_color {{ foreground }};
@define-color theme_unfocused_bg_color {{ background }};
@define-color theme_unfocused_base_color {{ darker_background }};
@define-color theme_unfocused_selected_bg_color {{ selection }};
@define-color theme_unfocused_selected_fg_color {{ selection_foreground }};
@define-color unfocused_insensitive_color {{ muted }};
@define-color unfocused_borders alpha({{ foreground }}, 0.12);
@define-color warning_color {{ yellow }};
@define-color error_color {{ red }};
@define-color success_color {{ green }};
@define-color destructive_color {{ red }};

@define-color content_view_bg {{ darker_background }};
@define-color text_view_bg {{ darker_background }};
