# Herdr theme generated by Omarchy from colors.toml.

[theme]
name = "terminal"

[theme.custom]
accent = "{{ accent }}"
panel_bg = "{{ background }}"
sidebar_bg = "{{ background }}"
active_row_bg = "{{ selection_background }}"
selection_bg = "{{ selection_background }}"
surface0 = "{{ selection_background }}"
surface1 = "{{ muted }}"
surface_dim = "{{ background }}"
overlay0 = "{{ muted }}"
overlay1 = "{{ muted }}"
text = "{{ foreground }}"
subtext0 = "{{ muted }}"
mauve = "{{ magenta }}"
green = "{{ green }}"
yellow = "{{ yellow }}"
red = "{{ red }}"
blue = "{{ blue }}"
teal = "{{ cyan }}"
peach = "{{ orange }}"
