name: omarchy
description: Follows the current Omarchy system theme

colors:
  background: "{{ background }}"
  ui_accent: "{{ accent }}"
  banner_accent: "{{ accent }}"
  banner_title: "{{ bright_foreground }}"
  banner_text: "{{ foreground }}"
  ui_text: "{{ foreground }}"
  banner_dim: "{{ dark_foreground }}"
  banner_border: "{{ muted }}"
  ui_border: "{{ muted }}"
  ui_ok: "{{ green }}"
  ui_warn: "{{ yellow }}"
  ui_error: "{{ red }}"
  ui_tool: "{{ accent }}"
  ui_thinking: "{{ dark_foreground }}"
  prompt: "{{ foreground }}"
  input_rule: "{{ accent }}"
  response_border: "{{ accent }}"
  status_bar_bg: "{{ dark_background }}"
  status_bar_text: "{{ foreground }}"
  status_bar_good: "{{ green }}"
  status_bar_warn: "{{ yellow }}"
  status_bar_critical: "{{ red }}"
  session_label: "{{ accent }}"
  session_border: "{{ muted }}"
  selection_bg: "{{ selection }}"
  completion_menu_bg: "{{ dark_background }}"
  completion_menu_current_bg: "{{ selection }}"
  syntax_string: "{{ green }}"
  syntax_number: "{{ yellow }}"
  syntax_keyword: "{{ magenta }}"
  syntax_comment: "{{ dark_foreground }}"
  diff_added: "{{ mix background green 15% }}"
  diff_removed: "{{ mix background red 15% }}"
  diff_added_word: "{{ green }}"
  diff_removed_word: "{{ red }}"
