{
  "$schema": "https://opencode.ai/theme.json",
  "defs": {
    "bg": "{{ background }}",
    "panel": "{{ darker_background }}",
    "element": "{{ darker_background }}",
    "fg": "{{ foreground }}",
    "bright": "{{ foreground }}",
    "dim": "{{ muted }}",
    "muted": "{{ muted }}",
    "accent": "{{ accent }}",
    "accentBright": "{{ bright_fg }}",
    "warm": "{{ red }}",
    "grey": "{{ muted }}",
    "keyword": "{{ magenta }}",
    "numeric": "{{ cyan }}",
    "type": "{{ yellow }}",
    "operator": "{{ blue }}",
    "line": "{{ darker_background }}",
    "addedBg": "{{ darker_background }}",
    "removedBg": "{{ darker_background }}",
    "ctxBg": "{{ background }}"
  },
  "theme": {
    "primary": "accent",
    "secondary": "numeric",
    "accent": "accentBright",
    "error": "accent",
    "warning": "grey",
    "success": "type",
    "info": "numeric",
    "text": "fg",
    "textMuted": "muted",
    "background": "bg",
    "backgroundPanel": "panel",
    "backgroundElement": "element",
    "border": "accent",
    "borderActive": "accentBright",
    "borderSubtle": "line",
    "backgroundMenu": "panel",
    "selectedListItemText": "bg",
    "diffAdded": "fg",
    "diffRemoved": "warm",
    "diffContext": "dim",
    "diffHunkHeader": "grey",
    "diffHighlightAdded": "bright",
    "diffHighlightRemoved": "accentBright",
    "diffAddedBg": "addedBg",
    "diffRemovedBg": "removedBg",
    "diffContextBg": "ctxBg",
    "diffLineNumber": "muted",
    "diffAddedLineNumberBg": "panel",
    "diffRemovedLineNumberBg": "panel",
    "markdownText": "fg",
    "markdownHeading": "numeric",
    "markdownLink": "accentBright",
    "markdownLinkText": "warm",
    "markdownCode": "accentBright",
    "markdownBlockQuote": "dim",
    "markdownEmph": "accent",
    "markdownStrong": "bright",
    "markdownHorizontalRule": "line",
    "markdownListItem": "accent",
    "markdownListEnumeration": "accentBright",
    "markdownImage": "numeric",
    "markdownImageText": "warm",
    "markdownCodeBlock": "fg",
    "syntaxComment": "muted",
    "syntaxKeyword": "keyword",
    "syntaxFunction": "operator",
    "syntaxVariable": "fg",
    "syntaxString": "warm",
    "syntaxNumber": "numeric",
    "syntaxType": "type",
    "syntaxOperator": "operator",
    "syntaxPunctuation": "dim"
  }
}
