{
  "primary": "{{ accent }}",
  "primaryText": "{{ selection_foreground }}",
  "primaryContainer": "{{ selection_background }}",
  "primaryContainerText": "{{ selection_foreground }}",
  "onPrimary": "{{ selection_foreground }}",
  "secondary": "{{ color2 }}",
  "secondaryText": "{{ background }}",
  "secondaryContainer": "{{ color8 }}",
  "secondaryContainerText": "{{ foreground }}",
  "tertiary": "{{ active_border_color }}",
  "tertiaryText": "{{ background }}",
  "tertiaryContainer": "{{ color12 }}",
  "tertiaryContainerText": "{{ foreground }}",
  "background": "{{ background }}",
  "backgroundText": "{{ foreground }}",
  "surface": "{{ background }}",
  "surfaceText": "{{ foreground }}",
  "surfaceVariant": "{{ color8 }}",
  "surfaceVariantText": "{{ foreground }}",
  "surfaceContainer": "{{ color10 }}",
  "outline": "{{ active_border_color }}",
  "shadow": "#000000",
  "inverseSurface": "{{ foreground }}",
  "inverseSurfaceText": "{{ background }}",
  "inversePrimary": "{{ accent }}"
}
