{
  "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
  "name": "Omarchy",
  "author": "Omarchy",
  "themes": [
    {
      "name": "Omarchy",
      "appearance": "{{ theme_type }}",
      "style": {
        "border": "{{ lighter_background }}",
        "border.variant": "{{ mix foreground background 70% }}80",
        "border.focused": "{{ accent }}",
        "border.selected": "{{ accent }}",
        "border.transparent": "#00000000",
        "border.disabled": "{{ lighter_background }}",
        "elevated_surface.background": "{{ dark_background }}",
        "surface.background": "{{ background }}",
        "background": "{{ background }}",
        "element.background": "{{ lighter_background }}",
        "element.hover": "{{ lighter_background }}99",
        "element.active": "{{ lighter_background }}cc",
        "element.selected": "{{ mix lighter_background accent 15% }}",
        "element.disabled": null,
        "drop_target.background": "{{ accent }}66",
        "ghost_element.background": null,
        "ghost_element.hover": "{{ lighter_background }}99",
        "ghost_element.active": "{{ lighter_background }}cc",
        "ghost_element.selected": "{{ mix lighter_background accent 15% }}",
        "ghost_element.disabled": null,
        "text": "{{ foreground }}",
        "text.muted": "{{ mix foreground background 30% }}",
        "text.placeholder": "{{ mix foreground background 55% }}",
        "text.disabled": "{{ mix foreground background 65% }}",
        "text.accent": "{{ accent }}",
        "icon": "{{ foreground }}",
        "icon.muted": "{{ mix foreground background 30% }}",
        "icon.disabled": "{{ mix foreground background 65% }}",
        "icon.placeholder": "{{ mix foreground background 55% }}",
        "icon.accent": "{{ accent }}",
        "status_bar.background": "{{ darker_background }}",
        "title_bar.background": "{{ darker_background }}",
        "toolbar.background": "{{ background }}",
        "tab_bar.background": "{{ dark_background }}",
        "tab.inactive_background": "{{ dark_background }}",
        "tab.active_background": "{{ background }}",
        "search.match_background": "{{ accent }}40",
        "panel.background": "{{ dark_background }}",
        "panel.focused_border": "{{ accent }}",
        "pane.focused_border": null,
        "scrollbar.thumb.background": "{{ mix foreground background 60% }}66",
        "scrollbar.thumb.hover_background": "{{ mix foreground background 60% }}99",
        "scrollbar.thumb.border": "{{ mix foreground background 60% }}66",
        "scrollbar.track.background": "{{ background }}",
        "scrollbar.track.border": "{{ lighter_background }}",
        "editor.foreground": "{{ foreground }}",
        "editor.background": "{{ background }}",
        "editor.gutter.background": "{{ background }}",
        "editor.subheader.background": "{{ lighter_background }}",
        "editor.active_line.background": "{{ lighter_background }}66",
        "editor.highlighted_line.background": null,
        "editor.line_number": "{{ mix foreground background 60% }}",
        "editor.active_line_number": "{{ foreground }}",
        "editor.invisible": "{{ mix foreground background 60% }}80",
        "editor.wrap_guide": "{{ lighter_background }}",
        "editor.active_wrap_guide": "{{ mix foreground background 60% }}",
        "editor.document_highlight.read_background": "{{ accent }}33",
        "editor.document_highlight.write_background": "{{ accent }}4d",
        "terminal.background": "{{ background }}",
        "terminal.foreground": "{{ foreground }}",
        "terminal.bright_foreground": "{{ bright_foreground }}",
        "terminal.dim_foreground": "{{ dark_foreground }}",
        "terminal.ansi.black": "{{ color0 }}",
        "terminal.ansi.bright_black": "{{ color8 }}",
        "terminal.ansi.dim_black": null,
        "terminal.ansi.red": "{{ color1 }}",
        "terminal.ansi.bright_red": "{{ color9 }}",
        "terminal.ansi.dim_red": null,
        "terminal.ansi.green": "{{ color2 }}",
        "terminal.ansi.bright_green": "{{ color10 }}",
        "terminal.ansi.dim_green": null,
        "terminal.ansi.yellow": "{{ color3 }}",
        "terminal.ansi.bright_yellow": "{{ color11 }}",
        "terminal.ansi.dim_yellow": null,
        "terminal.ansi.blue": "{{ color4 }}",
        "terminal.ansi.bright_blue": "{{ color12 }}",
        "terminal.ansi.dim_blue": null,
        "terminal.ansi.magenta": "{{ color5 }}",
        "terminal.ansi.bright_magenta": "{{ color13 }}",
        "terminal.ansi.dim_magenta": null,
        "terminal.ansi.cyan": "{{ color6 }}",
        "terminal.ansi.bright_cyan": "{{ color14 }}",
        "terminal.ansi.dim_cyan": null,
        "terminal.ansi.white": "{{ color7 }}",
        "terminal.ansi.bright_white": "{{ color15 }}",
        "terminal.ansi.dim_white": null,
        "link_text.hover": "{{ accent }}",
        "conflict": "{{ orange }}",
        "conflict.background": null,
        "conflict.border": null,
        "created": "{{ green }}",
        "created.background": null,
        "created.border": null,
        "deleted": "{{ red }}",
        "deleted.background": null,
        "deleted.border": null,
        "error": "{{ red }}",
        "error.background": "{{ dark_background }}",
        "error.border": "{{ red }}99",
        "hidden": "{{ mix foreground background 55% }}",
        "hidden.background": null,
        "hidden.border": null,
        "hint": "{{ mix foreground background 40% }}",
        "hint.background": null,
        "hint.border": null,
        "ignored": "{{ mix foreground background 55% }}",
        "ignored.background": null,
        "ignored.border": null,
        "info": "{{ blue }}",
        "info.background": null,
        "info.border": null,
        "modified": "{{ yellow }}",
        "modified.background": null,
        "modified.border": null,
        "predictive": "{{ mix foreground background 55% }}",
        "predictive.background": null,
        "predictive.border": null,
        "renamed": "{{ cyan }}",
        "renamed.background": null,
        "renamed.border": null,
        "success": "{{ green }}",
        "success.background": null,
        "success.border": null,
        "unreachable": "{{ mix foreground background 55% }}",
        "unreachable.background": null,
        "unreachable.border": null,
        "warning": "{{ yellow }}",
        "warning.background": "{{ dark_background }}",
        "warning.border": "{{ yellow }}99",
        "players": [
          { "cursor": "{{ accent }}", "background": "{{ accent }}", "selection": "{{ mix lighter_background accent 15% }}" },
          { "cursor": "{{ red }}", "background": "{{ red }}", "selection": "{{ red }}3d" },
          { "cursor": "{{ green }}", "background": "{{ green }}", "selection": "{{ green }}3d" },
          { "cursor": "{{ magenta }}", "background": "{{ magenta }}", "selection": "{{ magenta }}3d" },
          { "cursor": "{{ cyan }}", "background": "{{ cyan }}", "selection": "{{ cyan }}3d" }
        ],
        "syntax": {
          "attribute": { "color": "{{ yellow }}" },
          "boolean": { "color": "{{ orange }}" },
          "comment": { "color": "{{ mix foreground background 45% }}", "font_style": "italic" },
          "comment.doc": { "color": "{{ mix foreground background 45% }}", "font_style": "italic" },
          "constant": { "color": "{{ yellow }}" },
          "constructor": { "color": "{{ blue }}" },
          "embedded": { "color": "{{ foreground }}" },
          "emphasis": { "color": "{{ foreground }}", "font_style": "italic" },
          "emphasis.strong": { "color": "{{ foreground }}", "font_weight": 700 },
          "enum": { "color": "{{ cyan }}" },
          "function": { "color": "{{ blue }}" },
          "hint": { "color": "{{ mix foreground background 40% }}", "font_style": "italic" },
          "keyword": { "color": "{{ bright_magenta }}", "font_weight": 700 },
          "label": { "color": "{{ blue }}" },
          "link_text": { "color": "{{ magenta }}", "font_style": "italic" },
          "link_uri": { "color": "{{ blue }}", "font_style": "italic" },
          "number": { "color": "{{ orange }}" },
          "operator": { "color": "{{ bright_blue }}" },
          "predictive": { "color": "{{ mix foreground background 55% }}", "font_style": "italic" },
          "preproc": { "color": "{{ magenta }}" },
          "primary": { "color": "{{ foreground }}" },
          "property": { "color": "{{ cyan }}" },
          "punctuation": { "color": "{{ light_foreground }}" },
          "punctuation.bracket": { "color": "{{ light_foreground }}" },
          "punctuation.delimiter": { "color": "{{ light_foreground }}" },
          "punctuation.list_marker": { "color": "{{ cyan }}" },
          "punctuation.special": { "color": "{{ cyan }}" },
          "string": { "color": "{{ green }}" },
          "string.escape": { "color": "{{ magenta }}" },
          "string.regex": { "color": "{{ bright_cyan }}" },
          "string.special": { "color": "{{ blue }}" },
          "string.special.symbol": { "color": "{{ orange }}" },
          "tag": { "color": "{{ blue }}" },
          "text.literal": { "color": "{{ green }}" },
          "title": { "color": "{{ red }}", "font_weight": 700 },
          "type": { "color": "{{ yellow }}" },
          "variable": { "color": "{{ foreground }}" },
          "variable.special": { "color": "{{ red }}" },
          "variant": { "color": "{{ cyan }}" }
        }
      }
    }
  ]
}
