#!/bin/bash

# This hook is called with the current battery percentage and state every 30 seconds.
# It sends a notification when the battery level drops below a threshold.

BATTERY_LEVEL=$1
BATTERY_STATE=$2
BATTERY_THRESHOLD=10
NOTIFICATION_FLAG="/run/user/$UID/omarchy_battery_notified"

send_notification() {
  notify-send -u critical "󱐋 Time to recharge!" "Battery is down to ${1}%" -i battery-caution -t 30000
}

if [[ $BATTERY_STATE == "discharging" ]] && ((BATTERY_LEVEL <= BATTERY_THRESHOLD)); then
  if [[ ! -f $NOTIFICATION_FLAG ]]; then
    send_notification $BATTERY_LEVEL
    touch $NOTIFICATION_FLAG
  fi
else
  rm -f $NOTIFICATION_FLAG
fi
