#!/bin/bash

cd /opt/vivaldi/resources/vivaldi || exit 0

JS="style/omarchy.js"

sudo cp "${OMARCHY_PATH:-$HOME/.local/share/omarchy}/default/vivaldi/omarchy-theme-loader.js" "$JS"
sudo sed -i \
  -e "/omarchy-theme/d" -e "s|</head>|  <style id=\"omarchy-theme\"></style>\n&|" \
  -e "\|$JS|d"          -e "s|</head>|  <script src=\"$JS\"></script>\n&|" window.html

sudo touch style/omarchy.csv
sudo chown "$USER" style/omarchy.csv

omarchy-theme-set-browser
